# Generated by Django 4.0.3 on 2022-03-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_bid_active_alter_wishlist_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('House', 'House'), ('Kitchen', 'Kitchen'), ('Sport', 'Sport'), ('Cars', 'Cars'), ('Health', 'Health'), ('Food&Beverage', 'Food&Beverage'), ('Fashion', 'Fashion')], max_length=20, null=True),
        ),
    ]
