# Generated by Django 4.0 on 2022-01-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comments_bids'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(choices=[('Technology', 'Tech'), ('House Appliances', 'House'), ('Kitchen', 'Kitchen'), ('Sports Wear', 'Sport')], max_length=20),
        ),
    ]
