# Generated by Django 4.0.3 on 2022-03-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listing_image_alter_bid_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Image',
            field=models.ImageField(upload_to='auctions/static/media'),
        ),
    ]
