# Generated by Django 4.0 on 2022-01-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_category_alter_listing_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(choices=[('Technology', 'Tech'), ('House Appliances', 'House'), ('Kitchen', 'Kitchen'), ('Sports Wear', 'Sport')], max_length=20, null=True),
        ),
    ]
