# Generated by Django 4.0 on 2022-01-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('House', 'House'), ('Kitchen', 'Kitchen'), ('Sport', 'Sport')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
        ),
    ]
