# Generated by Django 4.0 on 2022-01-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category_alter_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
        ),
    ]
