# Generated by Django 4.0 on 2022-01-25 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_user_listing_user_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.user'),
        ),
    ]
