# Generated by Django 4.0 on 2022-01-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_comment_user_alter_listing_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(blank=True, choices=[('Tech', 'Tech'), ('House', 'House'), ('Kitchen', 'Kitchen'), ('Sport', 'Sport')], max_length=20, null=True),
        ),
    ]
