# Generated by Django 4.0 on 2022-01-26 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_wishlist_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='Listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auctions.listing'),
        ),
    ]
