# Generated by Django 4.0 on 2022-01-26 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_wishlist_listing_wishlist_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='Listing',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.listing'),
            preserve_default=False,
        ),
    ]
