# Generated by Django 4.0 on 2022-01-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_wishlist_listing_wishlist_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='Listing',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Listing',
            field=models.ManyToManyField(blank=True, to='auctions.Listing'),
        ),
    ]
