# Generated by Django 4.0 on 2022-01-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_remove_wishlist_listing_wishlist_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='Active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
